services:
  db:
    image: postgres:16
    container_name: my-new-api-db
    environment:
      POSTGRES_DB: mynewapi
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: